version: "3.9"

services:
  api:
    container_name: api
    image: rustapi:1.0.0
    env_file:
      - .env
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    networks:
      rust-api:

  db:
    container_name: db
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      rust-api:

volumes:
  pgdata: {}

networks:
  rust-api:
