# To use these .http files to test the API you need VSCODE & REST Client extension

# Don't forget to adapt the url (host & port) to your environment

############################################
#  Entrypoint : will answer with a welcome message
############################################
GET http://localhost:4444 HTTP/1.1


