# To use these .http files to test the API you need VSCODE & REST Client extension

# Don't forget to adapt the url (host & port) to your environment

################################################################
# TEAMS
################################################################

############################################
# get teams
############################################

GET http://localhost:4444/teams HTTP/1.1



############################################
# post team
############################################

POST http://localhost:4444/teams HTTP/1.1
Content-Type: application/json

{
    "name": "Ateam"
}

############################################
# post user fails with 422
############################################

POST http://localhost:4444/teams HTTP/1.1
Content-Type: application/json

{
    "name": 34
}